{% set version = "1.2.1" %}

package:
  name: tsl_robin_map
  version: {{ version }}

source:
  url: https://github.com/Tessil/robin-map/archive/v{{ version }}.tar.gz
  sha256: 2b54d2c1de2f73bea5c51d5dcbd64813a08caf1bfddcfdeee40ab74e9599e8e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/robin_map.h  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-robin-map/tsl-robin-mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-robin-map/tsl-robin-mapConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\tsl\robin_map.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tsl-robin-map\tsl-robin-mapConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tsl-robin-map\tsl-robin-mapConfigVersion.cmake exit 1  # [win]

about:
  home: https://github.com/Tessil/robin-map
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C++ fast hash map and hash set using robin hood hashing
  description: C++ fast hash map and hash set using robin hood hashing
  doc_url: https://tessil.github.io/robin-map/
  dev_url: https://github.com/Tessil/robin-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - mfansler
