{% set name = "tsl_robin_map" %}
{% set version = "1.0.1" %}
{% set sha256 = "b2ffdb623727cea852a66bddcb7fa6d938538a82b40e48294bb581fe086ef005" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Tessil/robin-map/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/robin_map.h  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-robin-map/tsl-robin-mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/tsl-robin-map/tsl-robin-mapConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\tsl\robin_map.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tsl-robin-map\tsl-robin-mapConfig.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\tsl-robin-map\tsl-robin-mapConfigVersion.cmake exit 1  # [win]

about:
  home: https://github.com/Tessil/robin-map
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C++ fast hash map and hash set using robin hood hashing
  description: C++ fast hash map and hash set using robin hood hashing
  doc_url: https://tessil.github.io/robin-map/
  dev_url: https://github.com/Tessil/robin-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - mfansler
